apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/juliofilizzola/kibana-eks-gitops.git
    targetRevision: HEAD
    path: apps/kibana
    helm:
      releaseName: elastic-stack
      chart: kibana
      repoURL: https://helm.elastic.co
      valuesObject:
        elasticsearchHosts: "http://elasticsearch-master.elastic-system:9200"
  destination:
    server: https://kubernetes.default.svc
    namespace: elastic-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
