apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/juliofilizzola/kibana-eks-gitops.git
    targetRevision: HEAD
    path: apps/kibana
  destination:
    server: https://kubernetes.default.svc
    namespace: elastic-system  # Onde Kibana roda
  syncPolicy:
    automated:
      prune: true
      selfHeal: true